[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
NEXT_PUBLIC_API_URL = "https://ask-mto.up.railway.app" 