[build]
builder = "NIXPACKS"
buildCommand = "pip install -r ask-mto-genai/requirements.txt"

[deploy]
startCommand = "python3 start_railway.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 