[build]
builder = "NIXPACKS"

# Take full control over the Nixpacks build process
[nixpacks]
# Force a specific python version for consistency
pythonVersion = "3.11"
# Explicitly define the install command, overriding any auto-detection
phases.install.cmds = ["pip install -r ask-mto-genai/requirements.txt"]

[deploy]
startCommand = "python3 start_railway.py"
healthcheckPath = "/"
# Increase healthcheck timeout one last time to be safe
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 