[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn ask-mto-genai.app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 