[build]
# Force Railway to use our Dockerfile and stop its automatic build process.
# This gives us 100% control over the environment.
builder = "dockerfile"
dockerfilePath = "ask-mto-genai/Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 