[build]
# Force Railway to use our Dockerfile and stop its automatic build process.
# This gives us 100% control over the environment.
builder = "dockerfile"

[deploy]
# The start command is now handled by the CMD instruction in the Dockerfile,
# so it is no longer needed here.
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 